### ISSUE TITLE
Philippines lookup

### ISSUE THREAD

**Issue by missinglink** [pelias/admin-lookup#18]
This document failed to intersect **any** polygons, it may be a data issue or a logic error?

http://pelias.mapzen.com/doc?id=osmnode:1562166367

```javascript
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "1562166367",
        "layer": "osmnode",
        "name": "Big Ben",
        "category": [
          "food",
          "retail",
          "nightlife"
        ],
        "address": {},
        "text": "Big Ben"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          124.239684,
          8.228061
        ]
      }
    }
  ],
  "bbox": [
    124.239684,
    8.228061,
    124.239684,
    8.228061
  ],
  "date": 1432667688558
}
```

**Comment by missinglink** [comment]
**[edit]** you can see in this screencap that the POI is inside the `admin0` although it's not quite inside the `admin1`:

![pic](http://missinglink.embed.s3.amazonaws.com/pelias-big-ben.png)

**Comment by orangejulius** [comment]
Looks like a similar issue to #22

**Comment by dianashk** [comment]
Add acceptance test

**Comment by dianashk** [comment]
Looks like the data has been fixed in OSM and it's not really a great acceptance test given the volatile nature of that record.
