### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by sheerun** [pelias/admin-lookup#28]
Hey. Could you release new patch version with commits from master? I have issues with microtime not compiling on newer node.

**Comment by orangejulius** [comment]
Oooh, please use https://github.com/pelias/wof-admin-lookup instead. I don't think any of our packages still depend on this one, but if they do, they should either be updated or (preferably) we would do the work of https://github.com/pelias/wof-admin-lookup/issues/48 and move it all back into this repo.

**Comment by sheerun** [comment]
Could you add deprecation notice in the README with link to the new repo?

**Comment by sheerun** [comment]
Oh, I see you did that week ago, never mind

**Comment by missinglink** [comment]
@orangejulius can we move this repo to https://github.com/pelias-deprecated ?
